In [16]:
import pandas as pd
df = pd.read_csv("../data/raw/imdb_scraped.csv")
df

,Title,Release Year,Certificate,Genres,IMDB Rating,Votes,Gross Revenue,genre_pull
0,Incredibles 2,(2018),PG,"\nAnimation, Action, Adventure",7.6,"280,820",$608.58M,comedy
1,Finding Dory,(2016),PG,"\nAnimation, Adventure, Comedy",7.3,"264,109",$486.30M,comedy
2,Frozen II,(2019),PG,"\nAnimation, Adventure, Comedy",6.8,"161,851",$477.37M,comedy
3,Shrek 2,(2004),PG,"\nAnimation, Adventure, Comedy",7.3,"447,248",$436.47M,comedy
4,Toy Story 4,(2019),G,"\nAnimation, Adventure, Comedy",7.7,"234,321",$434.04M,comedy
...,...,...,...,...,...,...,...,...
4345,Tangerines,(2013),Not Rated,"\nDrama, War",8.1,"45,371",$0.14M,war
4346,Tigerland,(2000),R,"\nDrama, War",7.0,"40,754",$0.14M,war
4347,The Warlords,(2007),R,"\nAction, Adventure, Drama",7.0,"26,667",$0.13M,war
4348,Centurion,(2010),R,"\nAction, Drama, History",6.3,"81,884",$0.12M,war
4349,Beasts of No Nation,(2015),TV-MA,"\nDrama, War",7.7,"79,605",$0.08M,war

In [24]:
top_1000_gross = (df
      .assign(gross_clean = lambda df_: df_["Gross Revenue"]
              .str.replace("$","")
              .str.replace("M","")
              .astype(float))
      .sort_values("gross_clean", ascending=False)
     .drop_duplicates(subset=["Title", "Release Year"])
     .reset_index(drop=True)[:1000])
top_1000_gross
# Need to figure out this error and see if there is a simple fix
# need to clean release year for matching for the omdb data

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  This is separate from the ipykernel package so we can avoid doing imports until

,Title,Release Year,Certificate,Genres,IMDB Rating,Votes,Gross Revenue,genre_pull,gross_clean
0,Star Wars: Episode VII - The Force Awakens,(2015),PG-13,"\nAction, Adventure, Sci-Fi",7.9,"902,824",$936.66M,adventure,936.66
1,Avengers: Endgame,(2019),PG-13,"\nAction, Adventure, Drama",8.4,"1,022,625",$858.37M,adventure,858.37
2,Avatar,(2009),PG-13,"\nAction, Adventure, Fantasy",7.9,"1,182,867",$760.51M,fantasy,760.51
3,Black Panther,(2018),PG-13,"\nAction, Adventure, Sci-Fi",7.3,"710,477",$700.06M,action,700.06
4,Avengers: Infinity War,(2018),PG-13,"\nAction, Adventure, Sci-Fi",8.5,"989,264",$678.82M,sci-fi,678.82
...,...,...,...,...,...,...,...,...,...
995,Father of the Bride Part II,(1995),PG,"\nComedy, Family, Romance",6.0,"37,349",$76.59M,family,76.59
996,Romancing the Stone,(1984),PG,"\nAction, Adventure, Comedy",6.9,"91,074",$76.57M,romance,76.57
997,Star Trek III: The Search for Spock,(1984),PG,"\nAction, Adventure, Sci-Fi",6.6,"79,102",$76.47M,sci-fi,76.47
998,Fantasia,(1940),G,"\nAnimation, Family, Fantasy",7.7,"93,963",$76.41M,musical,76.41
999,The Untouchables,(1987),R,"\nCrime, Drama, Thriller",7.9,"301,007",$76.27M,crime,76.27