In [5]:
import pandas as pd
df = pd.read_csv("../data/raw/tester_imdb_scrape.csv")
df

,Title,Release Year,Certificate,Genres,IMDB Rating,Votes,Gross Revenue,genre_pull
0,Incredibles 2,(2018),PG,"\nAnimation, Action, Adventure",7.6,"280,789",$608.58M,comedy
1,Finding Dory,(2016),PG,"\nAnimation, Adventure, Comedy",7.3,"264,085",$486.30M,comedy
2,Frozen II,(2019),PG,"\nAnimation, Adventure, Comedy",6.8,"161,827",$477.37M,comedy
3,Shrek 2,(2004),PG,"\nAnimation, Adventure, Comedy",7.3,"447,215",$436.47M,comedy
4,Toy Story 4,(2019),G,"\nAnimation, Adventure, Comedy",7.7,"234,294",$434.04M,comedy
...,...,...,...,...,...,...,...,...
4345,Tangerines,(2013),Not Rated,"\nDrama, War",8.1,"45,369",$0.14M,war
4346,Tigerland,(2000),R,"\nDrama, War",7.0,"40,752",$0.14M,war
4347,The Warlords,(2007),R,"\nAction, Adventure, Drama",7.0,"26,666",$0.13M,war
4348,Centurion,(2010),R,"\nAction, Drama, History",6.3,"81,882",$0.12M,war
4349,Beasts of No Nation,(2015),TV-MA,"\nDrama, War",7.7,"79,602",$0.08M,war

In [22]:
unique_titles = (df[["Title", "Release Year"]]
                 .drop_duplicates()
                 .assign(year=lambda df_: df_["Release Year"]
                         .str.replace("(","")
                         .str.replace(")",""))
                 .drop(columns="Release Year")
                 .to_csv("../data/raw/movies_list.csv",index=False))

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  after removing the cwd from sys.path.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """